-- CreateTable
CREATE TABLE "Client" (
    "id" TEXT NOT NULL PRIMARY KEY,
    "firstName" TEXT NOT NULL,
    "lastName" TEXT NOT NULL,
    "email" TEXT,
    "phone" TEXT,
    "phone2" TEXT,
    "cedula" TEXT,
    "clientType" TEXT NOT NULL,
    "source" TEXT,
    "status" TEXT NOT NULL DEFAULT 'ACTIVO',
    "searchType" TEXT,
    "searchZone" TEXT,
    "searchPropertyType" TEXT,
    "budgetMin" REAL,
    "budgetMax" REAL,
    "bedrooms" INTEGER,
    "bathrooms" INTEGER,
    "searchNotes" TEXT,
    "address" TEXT,
    "city" TEXT,
    "notes" TEXT,
    "driveLink" TEXT,
    "createdAt" DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
    "updatedAt" DATETIME NOT NULL
);

-- CreateTable
CREATE TABLE "Property" (
    "id" TEXT NOT NULL PRIMARY KEY,
    "title" TEXT NOT NULL,
    "propertyType" TEXT NOT NULL,
    "operationType" TEXT NOT NULL,
    "status" TEXT NOT NULL DEFAULT 'DISPONIBLE',
    "address" TEXT,
    "sector" TEXT,
    "city" TEXT,
    "state" TEXT,
    "country" TEXT NOT NULL DEFAULT 'República Dominicana',
    "referencePoint" TEXT,
    "salePrice" REAL,
    "rentPrice" REAL,
    "currency" TEXT NOT NULL DEFAULT 'USD',
    "maintenanceFee" REAL,
    "area" REAL,
    "landArea" REAL,
    "bedrooms" INTEGER,
    "bathrooms" INTEGER,
    "parkingSpots" INTEGER,
    "floors" INTEGER,
    "yearBuilt" INTEGER,
    "hasPool" BOOLEAN NOT NULL DEFAULT false,
    "hasGym" BOOLEAN NOT NULL DEFAULT false,
    "hasElevator" BOOLEAN NOT NULL DEFAULT false,
    "hasSecurity" BOOLEAN NOT NULL DEFAULT false,
    "hasGenerator" BOOLEAN NOT NULL DEFAULT false,
    "hasFurniture" BOOLEAN NOT NULL DEFAULT false,
    "hasAC" BOOLEAN NOT NULL DEFAULT false,
    "hasBalcony" BOOLEAN NOT NULL DEFAULT false,
    "hasGarden" BOOLEAN NOT NULL DEFAULT false,
    "driveLink" TEXT,
    "description" TEXT,
    "notes" TEXT,
    "ownerId" TEXT,
    "ownerName" TEXT,
    "ownerPhone" TEXT,
    "createdAt" DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
    "updatedAt" DATETIME NOT NULL,
    CONSTRAINT "Property_ownerId_fkey" FOREIGN KEY ("ownerId") REFERENCES "Client" ("id") ON DELETE SET NULL ON UPDATE CASCADE
);

-- CreateTable
CREATE TABLE "Deal" (
    "id" TEXT NOT NULL PRIMARY KEY,
    "dealType" TEXT NOT NULL,
    "status" TEXT NOT NULL DEFAULT 'EN_PROCESO',
    "clientId" TEXT,
    "propertyId" TEXT,
    "agreedPrice" REAL,
    "currency" TEXT NOT NULL DEFAULT 'USD',
    "commissionPct" REAL,
    "commissionAmount" REAL,
    "commissionPaid" BOOLEAN NOT NULL DEFAULT false,
    "commissionDate" DATETIME,
    "contractStartDate" DATETIME,
    "contractEndDate" DATETIME,
    "monthlyRent" REAL,
    "securityDeposit" REAL,
    "closingDate" DATETIME,
    "driveLink" TEXT,
    "notes" TEXT,
    "createdAt" DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
    "updatedAt" DATETIME NOT NULL,
    CONSTRAINT "Deal_clientId_fkey" FOREIGN KEY ("clientId") REFERENCES "Client" ("id") ON DELETE SET NULL ON UPDATE CASCADE,
    CONSTRAINT "Deal_propertyId_fkey" FOREIGN KEY ("propertyId") REFERENCES "Property" ("id") ON DELETE SET NULL ON UPDATE CASCADE
);
